### ISSUE TITLE
features all always empty

### ISSUE THREAD

**Issue by engmsaleh** [alippo-com/GrowthBook-SDK-Flutter#15]
I'm getting always the `features` map empty, Any advice?

This is how I have implemented it
```
User? user = await getUser();
  var attributes = {
    'user_id': user?.id ?? '',
    'user_name': user?.name ?? '',
    'user_email': user?.email ?? '',
    'user_phone': user?.phone ?? '',
  };
  gb = GBSDKBuilderApp(
    apiKey: AppConstants.GROWTHBOOK_API_KEY,
    attributes: attributes,
    growthBookTrackingCallBack: (gbExperiment, gbExperimentResult) {},
    hostURL: AppConstants.GROWTHBOOK_HOST_URL,
  ).initialize();
  logDebug('GrowthBook initialized');
```

**Comment by DK070202** [comment]
Hey, @engmsaleh  we have resolved it recently, can you try this?

replace your 
```yaml
  growthbook_sdk_flutter: ^1.0.0
```
to

```yaml
  growthbook_sdk_flutter: 
    git:
      url: https://github.com/alippo-com/GrowthBook-SDK-Flutter.git
      ref: master
```
